import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Next Variants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-blue-500 font-bold font-serif text-3xl">
          Welcome to the tailwindcss variant!
        </h1>

        <p className="font-serif font-light text-2xl">Get started by coding</p>
      </main>

      <footer>
        <p className="font-serif font-medium text-3xl">A next.ts footer</p>
      </footer>
    </div>
  );
}
