import Head from "next/head";

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>My Next Variants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" dark:bg-gray-900 flex max-w-screen min-h-screen items-center justify-center">
        <div className="flex flex-col dark:bg-gray-700 dark:text-gray-100 items-center font-serif w-1/3 justify-center rounded-3xl h-64 bg-gray-300 text-gray-700">
          <h1 className="text-3xl  font-bold mb-4">
            Tailwind darkmode
          </h1>
          <button className="w-24 font-sans hover:bg-red-500 rounded-lg h-12 bg-red-400">{"darkmode"}</button>
        </div>
      </main>

      <footer>
        <p className="font-serif font-medium text-3xl">A next.ts footer</p>
      </footer>
    </div>
  );
}
